### ISSUE TITLE
Perspective files are not portable

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/perspective-editor#47]
1. Take a Database dump from Env 1
2. Import said database to Env 2 (and clear caches)
3. Adjust perspectives using this editor
4. Commit and deploy the updated configuration file in Env 1.

Result:
All perspectives and views are blank in Env 1.

Tested in Pimcore 6.8.11 and 6.9.1 on PHP 7.4

**Comment by roland4432** [comment]
Hi @NiklasBr,
I don't think I get it quite right.

Why are you creating a dump from the DB? The perspectives / views are file-based only.

Are you editing perspectives in env 2 or 1? And when did the config get lost?

**Comment by NiklasBr** [comment]
The DB dump was just to ensure that both environments have the same data.

Maybe this bundle is expected to be configured manually on every server and the file should not be portable?

**Comment by roland4432** [comment]
The config file should be deterministic in both ways (storing / restoring).
So to reproduce
1. Config perspectives => save
2. Copy config to another pimcore instance => all is gone?

**Comment by NiklasBr** [comment]
Yes, all perspectives become blank for all users in Env2 when I do that, but in Env1 it looks as expected.

**Comment by fashxp** [comment]
can you check in what file the perspectives? 
maybe on env2 you have a `perspectives_env2.php` ?

**Comment by roland4432** [comment]
I just tried the following and sadly cannot reproduce the issue:

Setup 3 Pimcore instances: 2 with pimcore 6.9.4 and another one with pimcore 10.
I created perspectives in all 3 instances and copied them to the other 2. Then repeated the process so that all instances once delivered and consumed perspective setups. It's all working fine.

Could you maybe post one of your perspectives, that is not portable?

**Comment by NiklasBr** [comment]
I don't have it anymore, because it did not work we went back to building them by hand because it was faster and it worked.
