### ISSUE TITLE
[Improvement]: Add hidden field

### ISSUE THREAD

**Issue by Yivan** [pimcore/perspective-editor#53]
### Expected behavior

Having a checkbox "hidden" correspondaing to the yaml option hidding.

### Actual behavior

The is no such checkbox on the GUI

### Steps to reproduce

On the Pimcore demo, open the DAM perspective:

![image](https://user-images.githubusercontent.com/9025839/134365432-4cf4a4cf-60a1-4c75-8907-17cc9d7ecb45.png)

On the yaml config:

![image](https://user-images.githubusercontent.com/9025839/134365540-4326788f-6c4d-44bd-aa0e-79bf8f4c35fb.png)

Thanks.

**Comment by roland4432** [comment]
Hello @Yivan :)
Not sure if adding an element tree and not showing it afterwards is nonsense, but I guess your usecase is to define a tree for e.g. documents but not show it by default, only if the user decides to?

**Comment by Yivan** [comment]
Hi ! Yes I totally agree, it is a non sense : )
It is not my use case, it is the default Pimcore demo DAM perspective. I don't know why it was added.
So maybe this is the demo yaml file which is strange...
This option "hidden" could be use to keep the code iwhtout removing it for future activation for instance (maybe this was the idea behind ; ) )

My usecase is just opening the demo perspective, and test the perspective editor to check it breaks nothing.
But this hidden field not available in the perspective editor can lead problem, because on instance having already a yaml config, and installing the perspective editor, if just open and resave, thay will lost this hidden field, so panel hidden before saving will now show (as hidden field isn't managed by this extension). to prevent problem adding a checkbox hidden will make it more uptodate with yaml definition possibility of hidding.

**Comment by roland4432** [comment]
I will add the field for future conveniences as I, too, think, that preparing but not showing a tree is absolutely valid.

Note on overwriting fields, that are not accesible via the perspective editor:
This will not happen. The code is put that way, that it will always deep merge the options given in the yaml with the settings from the perspective editor. Since there are still some fields left that are not mapped in the GUI, I already thought about that and therefore made it this way.  
Hope this helps :)

**Comment by Yivan** [comment]
Thanks for adding it, it can be useful to prepare without publishing it.

This is great that it works by merging, this is more safe, this is good news! : )
Thanks a lot.
