### ISSUE TITLE
[Bug]: Not possible to open perspectives editor

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/perspective-editor#60]
### Expected behavior

It's possible to open Perspectives Editor

### Actual behavior

It's not possible to open Perspectives Editor.

### Steps to reproduce

1. Go to demo.pimcore.com/admin
2. Try to open Perspectives Editor
3. Getting an Error: Attempted to call an undefined method named "getCustomViewConfig" of class "Pimcore\Tool".

![image](https://user-images.githubusercontent.com/22637136/138281318-b481775b-4048-4be9-9294-6f51d3fbcfd1.png)

**Comment by fashxp** [comment]
Perspective editor is not yet compatible with Pimcore 10.2 ... 
https://github.com/pimcore/perspective-editor/pull/58 should fix that, will be merged asap and release will be most probably next wednesday.

**Comment by dvesh3** [comment]
@fashxp I think we have to restrict pimcore dependency to 10.1.5 version https://github.com/pimcore/perspective-editor/blob/1.1/composer.json#L12 on 1.1 version otherwise it will try to install latest version of Pimcore which is not compatible with this bundle. wdyt?

Note: https://github.com/pimcore/perspective-editor/pull/58 merged on branch 1.x

**Comment by fashxp** [comment]
yes good point!

**Comment by jdreesen** [comment]
As said in #61:

This won't help, as composer will not install the next release (`v1.1.1`), but as the current one (`v1.1.0`) still has `^10.0` it'll just install that.

Afaik this can't really be fixed...

**Comment by fashxp** [comment]
But with release of 1.2.0 it should be fixed then, shouldn't it?
For Pimcore >=10.2, 1.2 will be installed,
for Pimcore < 10.2, 1.1.1 will be installed.
